services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb+srv://saarcasmic:Qw3#Qw3#@cluster0.hbfujyw.mongodb.net/?appName=Cluster0
      - JWT_SECRET=4bafe17f5cbfc7017a8d11003d41474dca9eebfaa46a93023c80e5f6084b2fd03e7fcb90d386609d519c80bfc2285b92e8878b777dd2131d5d685a1051b35dfc
      - DB_USERNAME=saarcasmic
      - DB_PASSWORD=Qw3#Qw3#
      - DB_NAME=Cluster0
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app/backend
    command: >
      sh -c "node backend/server.js & python3 backend/ml/analysis.py"


  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
